apiVersion: v1
kind: Pod
metadata:
  name: hello-node
  labels:
    name: hello-node
spec:
  containers:
  - name: hello-node
    image: anjanaj/hello-node:latest
    ports:
      - containerPort: 3000